### ISSUE TITLE
Cant find config files for manual editing

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-qnap-qpkg#10]
As in #7 mentioned @nodecentral and me couldnt finde the cfg files for manula editing some "things".
But as this is starting to get a bit off topic in that mentioned issue i will start a new one.

I looked an dozens of folders the last days.
Is there any Documentation where to find the config files in the qnap file system?

**Comment by thopiekar** [comment]
Sorry for the late reply. I still don't get notifications on issues here :angry: 

If you mean the path when SSH'ing the NAS it should be something like: /share/CACHEDEV1_DATA/.qpkg/openHAB

But I can't tell whether it is in general this location since I only own a TS-228, which only comes with QTS 4.2.0. Some devices already come with QTS 4.3.x.
Also dependent on the count of the HDDs the path might change, but not sure.

**Comment by Confectrician** [comment]
No worries about the late reply. This is no sprint. :)
I am running 4.2.0 too at the moment so i will check for the files.
Maybe I will switch from qnap to a standalon raspberr pi for OpenHab Anyways.

I will check the folders for that .cfg file(s).

**Comment by nodecentral** [comment]
Hi @thopiekar 

I had looked through that directory but could not see a openhab.cfg file. As I mentioned in an earlier post there does seem to be some folders (like /Things/) that suggest you can modify the file in there. But it's not clear .  Having played with v1.x of openhab and having everything in the one file - maybe this is a new and key part of the v2.0 config experience ??

**Comment by thopiekar** [comment]
@nodecentral Yes, that's new in openhab2. Most of the configurations are now splitted into different files.

**Comment by JHCD** [comment]
Hi Thomas,
I have similar problems on my QNAP.
After some problems - I will create other issues for it - I've removed openHAB and installed it again.
I'm sure, that the /share/CACHEDEV1_DATA/.qpkg/openHAB folder was removed, but after reinstalling it again there were remains, so that I can't reinstall the add-ons f.e.
The folder "/share/CACHEDEV1_DATA/.qpkg/openHAB/distribution/addons" is empty.
Regards,
Jens

**Comment by thopiekar** [comment]
Odd behaviour.
Please retry with: https://github.com/openhab/openhab-qnap-qpkg/releases/tag/2.0.0-1

**Comment by Confectrician** [comment]
Hi,

Sorry for the late Request.
With the current version i was able to find the config files.

Since the live folder names are depending on some variables, there should maybe added a section in th e OH documentation about finding those files on a qnap.

**Comment by thopiekar** [comment]
No problem. Currently I also won't be able to help, because my TS-228 seems to be broken.
Already got problems with it from the beginning, that it is rebooting just randomly.
